### ISSUE TITLE
"pip install yaspi" error

### ISSUE THREAD

**Issue by keaixiaovv** [gulvarol/bsl1k#1]
Dear Author:
        When I install the package yaspi by "pip install yaspi", It always prompt "Could not find a version that satisfies the requirement yaspi". Is there any good solution or could you please order this package? Thank you very much!

**Comment by albanie** [comment]
Hi @keaixiaovv,

Thanks for flagging! That particular package (and potentially other items in the code) requires python 3.7. Apologies for not raising this in the README, we will update it.

**Comment by albanie** [comment]
Just a note to say that we've removed python 3.7 dependencies, so python 3.6 should now work :). Feel free to re-open if you still have problems.
