### ISSUE TITLE
pickle_frames.py

### ISSUE THREAD

**Issue by keaixiaovv** [gulvarol/bsl1k#2]
Hi my friend！When I run the file "pickle_frames.py", It has the error "ImportError: cannot import name 'BlockTimer", Does it need any library?
![image](https://user-images.githubusercontent.com/49025537/101854067-b81fe600-3b9b-11eb-917e-12cd6607a5ea.png)

**Comment by gulvarol** [comment]
Yes you can either install `zsvision` (https://pypi.org/project/zsvision/) and import as `from zsvision.zs_utils import  BlockTimer` or you can omit the lines using `BlockTimer`. Sorry for the inconvenience.
