### ISSUE TITLE
bsl1k info.pkl

### ISSUE THREAD

**Issue by NandhaKishorM** [gulvarol/bsl1k#7]
When will be the ./info/info.pkl file for bsl1k 1064 classes will be released?

**Comment by gulvarol** [comment]
Sorry for the inconvenience, this has taken longer than originally anticipated. Please follow the project page for updates on the data release: https://www.robots.ox.ac.uk/~vgg/research/bsl1k/ 

If what you need is only the 1064 class vocabulary, you can use this file: `misc/bsl1k/bsl1k_vocab.pkl`

**Comment by NandhaKishorM** [comment]
thanks for the update, is the bsl1k pretrained model public?

**Comment by gulvarol** [comment]
Yes, you can find all pretrained models from the links in the Readme.

**Comment by NandhaKishorM** [comment]
Thanks.
