### ISSUE TITLE
Sign spotting

### ISSUE THREAD

**Issue by iliasprc** [gulvarol/bsl1k#8]
Dear authors, could you provide the I3D model that is used for sign spotting or the model architecture  ?

**Comment by gulvarol** [comment]
Thanks for your question, the sign spotting experiment was done with the "Best model BSL-1K(m.5), last 20 frames, video pose pretrained". All the I3D models used in the experiments have their download links on the Readme. The corresponding model architecture file is also included in the code under `models` folder.
